import { ArrowLeft, ShieldCheck } from 'lucide-react'
import Footer from '../components/Footer.jsx'
import Header from '../components/Header.jsx'

const sections = [
  ['1. Quem somos', 'A GestFors Soluções Digitais desenvolve e opera produtos digitais e micro-SaaS para profissionais autônomos e negócios de nicho. Esta Política explica como tratamos dados pessoais quando você visita nosso site, entra em contato conosco ou utiliza nossos produtos.'],
  ['2. Dados que podemos coletar', 'Podemos coletar dados fornecidos diretamente por você, como nome, e-mail, empresa e conteúdo da mensagem enviada. Também podemos receber dados técnicos de navegação, como endereço IP, tipo de dispositivo, navegador, páginas acessadas e informações de diagnóstico, quando necessário para segurança e funcionamento do site.'],
  ['3. Como usamos os dados', 'Usamos os dados para responder solicitações, prestar suporte, melhorar produtos e experiências, manter a segurança da plataforma, cumprir obrigações legais e enviar comunicações relacionadas a serviços que você solicitou. Não vendemos dados pessoais.'],
  ['4. Bases legais', 'O tratamento pode se basear na execução de contrato ou de procedimentos preliminares, no cumprimento de obrigação legal, no exercício regular de direitos, no legítimo interesse ou no consentimento, conforme a finalidade e a legislação aplicável.'],
  ['5. Compartilhamento e segurança', 'Podemos compartilhar o mínimo necessário com provedores que apoiam hospedagem, infraestrutura, comunicação e segurança, sempre dentro de suas finalidades. Adotamos controles técnicos e administrativos razoáveis para proteger os dados contra acesso não autorizado, perda ou uso indevido.'],
  ['6. Retenção e direitos do titular', 'Mantemos os dados pelo período necessário às finalidades informadas e às obrigações legais. Você pode solicitar confirmação do tratamento, acesso, correção, anonimização, eliminação quando cabível, portabilidade, informação sobre compartilhamentos e revogação do consentimento.'],
  ['7. Cookies', 'Podemos utilizar cookies essenciais para o funcionamento do site e, quando aplicável, cookies de medição e preferência. Você pode controlar cookies nas configurações do navegador. A desativação de cookies essenciais pode afetar alguns recursos.'],
  ['8. Atualizações e contato', 'Esta política pode ser atualizada para refletir mudanças legais ou operacionais. A versão vigente estará sempre publicada nesta página. Para dúvidas ou solicitações relacionadas a dados pessoais, escreva para contato@gestfors.com.br.'],
]

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen bg-[#070a14] text-[#eef1fb]"><Header /><main className="relative overflow-hidden px-8 pb-24 pt-16 sm:pt-24"><div className="pointer-events-none absolute left-1/2 top-0 h-[360px] w-[620px] -translate-x-1/2 rounded-full bg-[#2f6bff]/10 blur-[110px]" /><div className="relative mx-auto max-w-[900px]"><a href="/" className="inline-flex items-center gap-2 text-sm text-[#9aa8c1] transition-colors hover:text-white"><ArrowLeft className="h-4 w-4" />Voltar para o início</a><div className="mt-10 border-b border-white/[0.1] pb-10"><div className="inline-flex items-center gap-2 rounded-full border border-[#283556] bg-[#0d1426] px-4 py-2 text-[10px] font-semibold tracking-[0.11em] text-[#b6c2e7]"><ShieldCheck className="h-3.5 w-3.5 text-[#3d7dff]" />GOVERNANÇA &amp; PRIVACIDADE</div><h1 className="mt-6 text-4xl font-bold tracking-[-0.035em] text-[#eef1ff] sm:text-5xl">Política de Privacidade</h1><p className="mt-5 max-w-2xl text-base leading-relaxed text-[#9aa8c1]">Transparência sobre o tratamento de dados pessoais na GestFors Soluções Digitais.</p><p className="mt-4 font-mono text-xs text-[#64728c]">Última atualização: 11 de setembro de 2026</p></div><div className="mt-10 space-y-8">{sections.map(([title, content]) => <section key={title}><h2 className="text-xl font-semibold text-[#eef1ff]">{title}</h2><p className="mt-3 text-[15px] leading-[1.75] text-[#a1aec5]">{content}</p></section>)}</div><div className="mt-12 rounded-xl border border-[#24365e] bg-[#10182d] p-5 text-sm leading-relaxed text-[#b0bdd4]">Para exercer seus direitos ou esclarecer qualquer dúvida sobre esta política, envie uma mensagem para <a className="text-[#5b9bff] hover:text-white" href="mailto:contato@gestfors.com.br">contato@gestfors.com.br</a>.</div></div></main><Footer /></div>
  )
}
